#!/usr/bin/python3
import sys

def factorize(n):
    for a in range(2, n):
        if n % a == 0:
            b = n // a
            return min(a,b), max(a, b)
    return None, None

def main(filename):
    with open(filename, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factor1, factor2 = factorize(n)
        if factor1 is not None:
            print(f"{n}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factor <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)
